import { Category, Subcategory, Product, HomepageSettings, StoreSettings } from '../../types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-boys',
    name: 'BOYS',
    slug: 'boys',
    description: 'Little Style. Big Dreams. Smart ethnic sets, casuals & party wear.',
    coverImage: 'https://images.unsplash.com/photo-1519457431-44ccd64a579b?auto=format&fit=crop&w=800&q=80',
    isActive: true,
    displayOrder: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-girls',
    name: 'GIRLS',
    slug: 'girls',
    description: 'Pretty Looks. Bright Vibes. Beautiful frocks, anarkalis & western ensembles.',
    coverImage: 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=800&q=80',
    isActive: true,
    displayOrder: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-women',
    name: 'WOMEN',
    slug: 'women',
    description: 'Effortless Style Every Day. Handcrafted kurtis, festive sets & occasion wear.',
    coverImage: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
    isActive: true,
    displayOrder: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-mens',
    name: 'MENS',
    slug: 'mens',
    description: 'Classic Looks. Modern You. Crisp shirts, celebratory kurtas & tailored trousers.',
    coverImage: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=800&q=80',
    isActive: true,
    displayOrder: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_SUBCATEGORIES: Subcategory[] = [
  // Boys Subcategories
  {
    id: 'sub-boys-ethnic',
    categoryId: 'cat-boys',
    name: 'Ethnic Wear',
    slug: 'ethnic-wear',
    description: 'Festive dhoti sets, pathani suits, and embroidered jackets.',
    coverImage: 'https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub-boys-tshirts',
    categoryId: 'cat-boys',
    name: 'T-Shirts',
    slug: 't-shirts',
    description: 'Soft combed cotton printed and solid tees for everyday comfort.',
    coverImage: 'https://images.unsplash.com/photo-1519457431-44ccd64a579b?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub-boys-jeans',
    categoryId: 'cat-boys',
    name: 'Jeans',
    slug: 'jeans',
    description: 'Durable stretch denim and cargo trousers for active kids.',
    coverImage: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub-boys-casual',
    categoryId: 'cat-boys',
    name: 'Casual Wear',
    slug: 'casual-wear',
    description: 'Coordinated shirt and shorts sets for weekend outings.',
    coverImage: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub-boys-kurta',
    categoryId: 'cat-boys',
    name: 'Kurta Pyjama',
    slug: 'kurta-pyjama',
    description: 'Regal silk and cotton kurta pyjama pairs for festivals.',
    coverImage: 'https://images.unsplash.com/photo-1597983073493-88cd35cf93b0?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // Girls Subcategories
  {
    id: 'sub-girls-frocks',
    categoryId: 'cat-girls',
    name: 'Frocks',
    slug: 'frocks',
    description: 'Princess ballgowns, birthday frocks, and layered net party dresses.',
    coverImage: 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub-girls-ethnic',
    categoryId: 'cat-girls',
    name: 'Ethnic Wear',
    slug: 'ethnic-wear',
    description: 'Traditional lehenga cholis, sharara suits, and festive anarkalis.',
    coverImage: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub-girls-western',
    categoryId: 'cat-girls',
    name: 'Western Wear',
    slug: 'western-wear',
    description: 'Jumpsuits, dungarees, and trendy coordinates.',
    coverImage: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub-girls-tops',
    categoryId: 'cat-girls',
    name: 'T-Shirts & Tops',
    slug: 't-shirts-tops',
    description: 'Embroidered peplum tops, sequin tees, and ruffled blouses.',
    coverImage: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub-girls-jeans',
    categoryId: 'cat-girls',
    name: 'Jeans',
    slug: 'jeans',
    description: 'Floral embroidered denims, wide-leg pants & jeggings.',
    coverImage: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // Women Subcategories
  {
    id: 'sub-women-kurtis',
    categoryId: 'cat-women',
    name: 'Kurtis',
    slug: 'kurtis',
    description: 'Straight cut, A-line, and flared cotton and rayon kurtis.',
    coverImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub-women-kurti-sets',
    categoryId: 'cat-women',
    name: 'Kurti Sets',
    slug: 'kurti-sets',
    description: 'Matching kurti, pant, and dupatta sets in pure cotton and silk blends.',
    coverImage: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub-women-tops',
    categoryId: 'cat-women',
    name: 'Tops',
    slug: 'tops',
    description: 'Contemporary shirts, tunic tops, and floral fusion wear.',
    coverImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub-women-ethnic',
    categoryId: 'cat-women',
    name: 'Ethnic Wear',
    slug: 'ethnic-wear',
    description: 'Opulent Anarkali gowns, Banarasi dupattas, and bridal festive wear.',
    coverImage: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub-women-jeans',
    categoryId: 'cat-women',
    name: 'Jeans',
    slug: 'jeans',
    description: 'High-waist mom jeans, ankle-length skinnies, and comfort denim.',
    coverImage: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // Mens Subcategories
  {
    id: 'sub-mens-shirts',
    categoryId: 'cat-mens',
    name: 'Shirts',
    slug: 'shirts',
    description: 'Formal oxford weaves, pure linen casual shirts, and printed party shirts.',
    coverImage: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub-mens-tshirts',
    categoryId: 'cat-mens',
    name: 'T-Shirts',
    slug: 't-shirts',
    description: 'Classic polo t-shirts, crew necks, and henleys in breathable cotton.',
    coverImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub-mens-pants',
    categoryId: 'cat-mens',
    name: 'Pants',
    slug: 'pants',
    description: 'Formal trousers, stretch chinos, and tailored casual trousers.',
    coverImage: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub-mens-kurta',
    categoryId: 'cat-mens',
    name: 'Kurta Pyjama',
    slug: 'kurta-pyjama',
    description: 'Festive Lucknowi chikan kurtas, Modi jackets, and wedding sherwanis.',
    coverImage: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub-mens-shorts',
    categoryId: 'cat-mens',
    name: 'Shorts',
    slug: 'shorts',
    description: 'Chino shorts and comfortable summer casual bermudas.',
    coverImage: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&w=600&q=80',
    isActive: true,
    displayOrder: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // GIRLS PRODUCTS
  {
    id: 'MD-GIRLS-FROCK-0012',
    categoryId: 'cat-girls',
    subcategoryId: 'sub-girls-frocks',
    name: 'Pink Embroidered Party Frock',
    slug: 'pink-embroidered-party-frock',
    description: 'A magical party frock crafted with soft multilayered tulle and intricate floral embroidery on the bodice. Features a satin inner lining for gentle comfort against young skin, delicate cap sleeves, and a shimmering back tie-up bow. Perfect for birthdays, weddings, and special celebrations.',
    shortDescription: 'Delicate floral embroidered net frock with soft satin lining and bow.',
    mrp: 1799,
    sellingPrice: 1299,
    showPrice: true,
    status: 'ACTIVE',
    isFeatured: true,
    isNewArrival: true,
    isTrending: true,
    brand: 'Modern Princess',
    fabric: 'Soft Net & Satin',
    pattern: 'Embroidered Floral',
    occasion: 'Party & Festive',
    fit: 'Regular Fit flared',
    sleeve: 'Cap Sleeves',
    neck: 'Round Neck',
    washCare: 'Dry Clean or Gentle Hand Wash',
    countryOfOrigin: 'India',
    tags: ['Party Wear', 'Bestseller', 'Festive', 'New'],
    sizes: ['22', '24', '26', '28', '30'],
    colours: [
      {
        id: 'c-pink',
        name: 'Blush Pink',
        hex: '#F4B7BD',
        images: [
          'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80',
        ],
      },
      {
        id: 'c-blue',
        name: 'Sky Blue',
        hex: '#87CEEB',
        images: [
          'https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?auto=format&fit=crop&w=800&q=80',
        ],
      },
      {
        id: 'c-yellow',
        name: 'Pastel Yellow',
        hex: '#FDE047',
        images: [
          'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=800&q=80',
        ],
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'MD-GIRLS-FROCK-0025',
    categoryId: 'cat-girls',
    subcategoryId: 'sub-girls-frocks',
    name: 'Floral Cotton Summer Frock',
    slug: 'floral-cotton-summer-frock',
    description: 'Lightweight, breathable pure cotton frock adorned with cheerful hand-block floral motifs. Includes a matching hair accessory band and soft pearl buttons at the back.',
    shortDescription: 'Pure cotton breathable frock with vintage botanical florals.',
    mrp: 1299,
    sellingPrice: 899,
    showPrice: true,
    status: 'ACTIVE',
    isFeatured: false,
    isNewArrival: true,
    isTrending: false,
    brand: 'Modern Littles',
    fabric: '100% Breathable Cotton',
    pattern: 'Floral Print',
    occasion: 'Casual & Daywear',
    fit: 'A-Line Comfort',
    sleeve: 'Sleeveless',
    neck: 'Sweetheart Neck',
    washCare: 'Machine Wash Cold',
    countryOfOrigin: 'India',
    tags: ['Casual', 'Summer', 'New'],
    sizes: ['20', '22', '24', '26', '28'],
    colours: [
      {
        id: 'c-peach',
        name: 'Soft Peach',
        hex: '#FFDAB9',
        images: [
          'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80',
        ],
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'MD-GIRLS-ETHNIC-0038',
    categoryId: 'cat-girls',
    subcategoryId: 'sub-girls-ethnic',
    name: 'Royal Brocade Lehenga Choli Set',
    slug: 'royal-brocade-lehenga-choli-set',
    description: 'Opulent banarasi brocade lehenga paired with a zari embroidered velvet choli and a delicate organza dupatta with gold scalloped lace border.',
    shortDescription: 'Banarasi brocade lehenga with zari choli and scalloped dupatta.',
    mrp: 3499,
    sellingPrice: 2499,
    showPrice: true,
    status: 'ACTIVE',
    isFeatured: true,
    isNewArrival: false,
    isTrending: true,
    brand: 'Modern Heritage',
    fabric: 'Banarasi Silk & Velvet',
    pattern: 'Zari Weave',
    occasion: 'Wedding & Festive',
    fit: 'Flared Lehenga',
    sleeve: 'Elbow Sleeves',
    neck: 'Boat Neck',
    washCare: 'Dry Clean Only',
    countryOfOrigin: 'India',
    tags: ['Wedding', 'Festive', 'Premium', 'Bestseller'],
    sizes: ['24', '26', '28', '30', '32'],
    colours: [
      {
        id: 'c-maroon',
        name: 'Royal Maroon & Gold',
        hex: '#800020',
        images: [
          'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
        ],
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // WOMEN PRODUCTS
  {
    id: 'MD-WOMEN-KURTI-0073',
    categoryId: 'cat-women',
    subcategoryId: 'sub-women-kurti-sets',
    name: 'Printed Cotton Kurti Pant Set with Dupatta',
    slug: 'printed-cotton-kurti-pant-set',
    description: 'An elegant 3-piece ensemble featuring a straight-fit calf-length kurti with intricate threadwork neckline, tailored straight pants with pockets, and a featherlight mulmul dupatta. Crafted from 60x60 premium cotton for all-day breathability and sophistication.',
    shortDescription: '3-Piece pure cotton straight kurti, cigarette pants & mulmul dupatta.',
    mrp: 2799,
    sellingPrice: 1899,
    showPrice: true,
    status: 'ACTIVE',
    isFeatured: true,
    isNewArrival: true,
    isTrending: true,
    brand: 'Modern Elegance',
    fabric: 'Pure Cotton (60s)',
    pattern: 'Hand-Screen Print with Gota Patti',
    occasion: 'Festive & Office Chic',
    fit: 'Straight Fit',
    sleeve: '3/4th Sleeves',
    neck: 'Mandarin V-Notch',
    washCare: 'Hand Wash Separately',
    countryOfOrigin: 'India',
    tags: ['Bestseller', 'Festive', 'Premium', 'New'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colours: [
      {
        id: 'c-sage',
        name: 'Sage Green',
        hex: '#9CAF88',
        images: [
          'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
        ],
      },
      {
        id: 'c-mustard',
        name: 'Mustard Ochre',
        hex: '#DDA025',
        images: [
          'https://images.unsplash.com/photo-1597983073493-88cd35cf93b0?auto=format&fit=crop&w=800&q=80',
        ],
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'MD-WOMEN-KURTI-0089',
    categoryId: 'cat-women',
    subcategoryId: 'sub-women-kurtis',
    name: 'Party Wear Silk Chanderi Kurti',
    slug: 'party-wear-silk-chanderi-kurti',
    description: 'Exclusive handwoven Chanderi silk kurti with delicate Kashmiri zari embroidery on yoke and hemline. Designed for grand family gatherings and wedding functions. Comes with pure butter-crepe lining for royal drape and comfort.',
    shortDescription: 'Handwoven Chanderi silk kurti with regal zari embroidery.',
    mrp: 3999,
    sellingPrice: 2899,
    showPrice: false, // HIDDEN PRICE DEMO!
    priceRequestText: 'Price available on request',
    status: 'ACTIVE',
    isFeatured: true,
    isNewArrival: false,
    isTrending: true,
    brand: 'Modern Haute Couture',
    fabric: 'Pure Chanderi Silk with Zari',
    pattern: 'Kashmiri Hand Embroidered',
    occasion: 'Wedding & Grand Celebrations',
    fit: 'Flared Anarkali',
    sleeve: 'Full Sleeves',
    neck: 'Round Neck with Keyhole',
    washCare: 'Strictly Dry Clean Only',
    countryOfOrigin: 'India',
    tags: ['Wedding', 'Festive', 'Premium', 'Exclusive'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colours: [
      {
        id: 'c-royal-wine',
        name: 'Royal Wine',
        hex: '#581845',
        images: [
          'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
        ],
      },
      {
        id: 'c-emerald',
        name: 'Emerald Green',
        hex: '#097969',
        images: [
          'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
        ],
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'MD-WOMEN-ETHNIC-0095',
    categoryId: 'cat-women',
    subcategoryId: 'sub-women-ethnic',
    name: 'Georgette Tiered Anarkali Gown',
    slug: 'georgette-tiered-anarkali-gown',
    description: 'Floor-length flared Georgette Anarkali gown enriched with sequins and mirror-style embroidery across the front panel. Lightweight micro-can-can attached to the hem for magnificent volume.',
    shortDescription: 'Floor-length flowy georgette gown with sparkling sequin work.',
    mrp: 4999,
    sellingPrice: 3499,
    showPrice: true,
    status: 'ACTIVE',
    isFeatured: false,
    isNewArrival: true,
    isTrending: true,
    brand: 'Modern Heritage',
    fabric: 'Heavy Faux Georgette',
    pattern: 'Sequin & Resham Work',
    occasion: 'Sangeet & Reception',
    fit: 'Full Flared Anarkali',
    sleeve: 'Churidar Sleeves',
    neck: 'Deep Round Neck',
    washCare: 'Dry Clean Only',
    countryOfOrigin: 'India',
    tags: ['Party Wear', 'Wedding', 'New'],
    sizes: ['M', 'L', 'XL'],
    colours: [
      {
        id: 'c-midnight-navy',
        name: 'Midnight Navy',
        hex: '#000080',
        images: [
          'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
        ],
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // MENS PRODUCTS
  {
    id: 'MD-MENS-SHIRT-0094',
    categoryId: 'cat-mens',
    subcategoryId: 'sub-mens-shirts',
    name: 'Classic Oxford Pure Cotton Shirt',
    slug: 'classic-oxford-pure-cotton-shirt',
    description: 'Timeless button-down shirt woven from 100% fine Egyptian cotton in an Oxford basket-weave structure. Features reinforced mother-of-pearl buttons, curved hemline, and a neat button-down collar that maintains structure all day.',
    shortDescription: 'Premium Oxford weave 100% cotton shirt with button-down collar.',
    mrp: 1999,
    sellingPrice: 1399,
    showPrice: true,
    status: 'ACTIVE',
    isFeatured: true,
    isNewArrival: false,
    isTrending: true,
    brand: 'Modern Gentleman',
    fabric: '100% Oxford Cotton',
    pattern: 'Solid Texture',
    occasion: 'Formal & Semi-Formal',
    fit: 'Tailored Slim Fit',
    sleeve: 'Full Sleeves',
    neck: 'Button-Down Collar',
    washCare: 'Machine Wash Warm, Steam Iron',
    countryOfOrigin: 'India',
    tags: ['Bestseller', 'Casual', 'Premium'],
    sizes: ['38 (S)', '40 (M)', '42 (L)', '44 (XL)', '46 (XXL)'],
    colours: [
      {
        id: 'c-white',
        name: 'Crisp White',
        hex: '#FFFFFF',
        images: [
          'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=800&q=80',
        ],
      },
      {
        id: 'c-powder-blue',
        name: 'Powder Blue',
        hex: '#B0E0E6',
        images: [
          'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
        ],
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'MD-MENS-KURTA-0102',
    categoryId: 'cat-mens',
    subcategoryId: 'sub-mens-kurta',
    name: 'Lucknowi Embroidered Kurta Pyjama Set',
    slug: 'lucknowi-embroidered-kurta-pyjama-set',
    description: 'Traditional Lucknowi Chikan hand-embroidered kurta accompanied by a crisp white churidar pyjama. Adorned with tone-on-tone threadwork and subtle mirror highlights.',
    shortDescription: 'Artisanal Chikan embroidery kurta set with cotton churidar.',
    mrp: 3299,
    sellingPrice: 2299,
    showPrice: true,
    status: 'ACTIVE',
    isFeatured: true,
    isNewArrival: true,
    isTrending: false,
    brand: 'Modern Heritage',
    fabric: 'Cotton Silk Blend',
    pattern: 'Lucknowi Chikan Handwork',
    occasion: 'Festivals, Eid, Diwali & Puja',
    fit: 'Comfort Regular Fit',
    sleeve: 'Full Sleeves',
    neck: 'Mandarin Collar with Buttons',
    washCare: 'Gentle Hand Wash in Cold Water',
    countryOfOrigin: 'India',
    tags: ['Festive', 'Wedding', 'New', 'Premium'],
    sizes: ['M (38)', 'L (40)', 'XL (42)', 'XXL (44)'],
    colours: [
      {
        id: 'c-ivory',
        name: 'Pearl Ivory',
        hex: '#FFFFF0',
        images: [
          'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=800&q=80',
        ],
      },
      {
        id: 'c-pista',
        name: 'Pista Green',
        hex: '#93C572',
        images: [
          'https://images.unsplash.com/photo-1597983073493-88cd35cf93b0?auto=format&fit=crop&w=800&q=80',
        ],
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'MD-MENS-SHIRT-0115',
    categoryId: 'cat-mens',
    subcategoryId: 'sub-mens-shirts',
    name: 'Pure French Linen Casual Shirt',
    slug: 'pure-french-linen-casual-shirt',
    description: 'Breathable, relaxed-fit shirt made of premium yarn-dyed French flax linen. Features a band collar and roll-up sleeve tabs for quintessential resort and weekend elegance.',
    shortDescription: '100% pure breathable linen shirt with band collar.',
    mrp: 2499,
    sellingPrice: 1799,
    showPrice: false, // HIDDEN PRICE DEMO!
    priceRequestText: 'Contact us for price',
    status: 'ACTIVE',
    isFeatured: false,
    isNewArrival: true,
    isTrending: true,
    brand: 'Modern Gentleman',
    fabric: '100% Pure Flax Linen',
    pattern: 'Melange Texture',
    occasion: 'Resort, Weekend & Casual',
    fit: 'Relaxed Fit',
    sleeve: 'Full Sleeves with Tab',
    neck: 'Mandarin Band Collar',
    washCare: 'Cold Wash, Dry in Shade',
    countryOfOrigin: 'India',
    tags: ['Casual', 'Premium', 'New'],
    sizes: ['M', 'L', 'XL'],
    colours: [
      {
        id: 'c-olive',
        name: 'Earthy Olive',
        hex: '#708238',
        images: [
          'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
        ],
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // BOYS PRODUCTS
  {
    id: 'MD-BOYS-ETHNIC-0044',
    categoryId: 'cat-boys',
    subcategoryId: 'sub-boys-ethnic',
    name: 'Boys Silk Kurta with Jacquard Nehru Jacket & Dhoti Set',
    slug: 'boys-kurta-nehru-jacket-dhoti-set',
    description: 'A handsome 3-piece celebratory set featuring a silk blend kurta, readymade elasticated stitched dhoti pant, and a metallic woven jacquard Nehru jacket with brooch pin.',
    shortDescription: '3-Piece royal jacquard jacket, kurta and dhoti ensemble.',
    mrp: 2499,
    sellingPrice: 1699,
    showPrice: true,
    status: 'ACTIVE',
    isFeatured: true,
    isNewArrival: true,
    isTrending: true,
    brand: 'Modern Littles',
    fabric: 'Art Silk & Brocade Jacquard',
    pattern: 'Woven Jacquard Motifs',
    occasion: 'Wedding & Festive',
    fit: 'Regular Ethnic Fit',
    sleeve: 'Full Sleeves',
    neck: 'Mandarin Collar',
    washCare: 'Dry Clean Recommended',
    countryOfOrigin: 'India',
    tags: ['Festive', 'Wedding', 'Bestseller', 'New'],
    sizes: ['22 (2-3Y)', '24 (3-4Y)', '26 (5-6Y)', '28 (7-8Y)', '30 (9-10Y)'],
    colours: [
      {
        id: 'c-gold-red',
        name: 'Gold & Crimson Red',
        hex: '#DC143C',
        images: [
          'https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1597983073493-88cd35cf93b0?auto=format&fit=crop&w=800&q=80',
        ],
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'MD-BOYS-CASUAL-0051',
    categoryId: 'cat-boys',
    subcategoryId: 'sub-boys-casual',
    name: 'Boys Denim Dungaree and Striped Tee Set',
    slug: 'boys-denim-dungaree-striped-tee-set',
    description: 'Adorably styled washed denim dungaree with adjustable metal buckles and side buttons, paired with a soft combed cotton navy-and-white striped t-shirt.',
    shortDescription: 'Washed denim dungarees with striped crew tee.',
    mrp: 1499,
    sellingPrice: 999,
    showPrice: true,
    status: 'OUT_OF_STOCK', // OUT OF STOCK DEMO!
    isFeatured: false,
    isNewArrival: false,
    isTrending: true,
    brand: 'Modern Littles',
    fabric: 'Cotton Denim & 100% Cotton Tee',
    pattern: 'Washed Denim & Stripes',
    occasion: 'Casual & Playwear',
    fit: 'Comfort Fit',
    sleeve: 'Short Sleeves',
    neck: 'Round Neck',
    washCare: 'Machine Wash Warm',
    countryOfOrigin: 'India',
    tags: ['Casual', 'Trending'],
    sizes: ['20 (1-2Y)', '22 (2-3Y)', '24 (3-4Y)'],
    colours: [
      {
        id: 'c-indigo',
        name: 'Classic Indigo',
        hex: '#4B0082',
        images: [
          'https://images.unsplash.com/photo-1519457431-44ccd64a579b?auto=format&fit=crop&w=800&q=80',
        ],
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_HOMEPAGE_SETTINGS: HomepageSettings = {
  sections: {
    hero: true,
    categories: true,
    featured: true,
    newArrivals: true,
    trending: true,
    promoBanner: true,
    whyUs: true,
    customSection: true,
  },
  sectionOrder: ['hero', 'categories', 'featured', 'newArrivals', 'trending', 'promoBanner', 'whyUs', 'customSection'],
  hero: {
    title: 'MODERN DRESSES',
    subtitle: 'FASHION FOR EVERY GENERATION',
    description: 'Discover premium handpicked ethnic wear, party dresses, kurtis, and timeless clothing for boys, girls, women and men at Bidar’s favorite boutique destination.',
    primaryBtnText: 'SHOP COLLECTION',
    primaryBtnLink: '/women',
    secondaryBtnText: 'EXPLORE KIDS WEAR',
    secondaryBtnLink: '/girls',
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1600&q=85',
  },
  promoBanner: {
    badge: 'FESTIVE EDIT 2025',
    heading: 'Grand Celebrations Deserve Grand Styles',
    description: 'Explore our latest collection of bridal anarkalis, regal sherwanis, and charming kids party wear crafted with authentic Indian textiles.',
    btnText: 'VIEW FESTIVE STYLES',
    btnLink: '/women/ethnic-wear',
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1600&q=85',
  },
  customSection: {
    badge: 'BIDAR SPECIAL',
    heading: 'Handcrafted Heritage & Contemporary Silhouettes',
    description: 'Each piece at Modern Dresses is thoughtfully curated for perfection in fabric, stitching, and finish. Visit our boutique or connect directly on WhatsApp for personalized styling advice.',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1200&q=80',
    btnText: 'CONNECT ON WHATSAPP',
    btnLink: 'https://wa.me/918951337609',
  },
  visibleCategoryIds: ['cat-boys', 'cat-girls', 'cat-women', 'cat-mens'],
};

export const INITIAL_STORE_SETTINGS: StoreSettings = {
  storeName: 'Modern Dresses',
  tagline: 'Fashion for Every Generation',
  location: 'Bidar, Karnataka',
  phone: '+91 8951337609',
  whatsappNumber: '8951337609', // Per user's explicit instruction
  email: 'info@moderndresses.com',
  address: 'Main Market Road, Near Gandhi Gunj, Bidar - 585401, Karnataka, India',
  businessHours: 'Monday - Sunday: 10:00 AM - 9:30 PM',
  instagram: 'https://instagram.com/moderndressesbidar',
  facebook: 'https://facebook.com/moderndressesbidar',
  footerText: 'Modern Dresses is Bidar’s premier fashion boutique offering curated collections for kids, women, and men. Order seamlessly through direct WhatsApp consultation.',
  aboutStory: 'Established with a passion for exceptional quality and timeless fashion, Modern Dresses has been the trusted destination for generations of families in Bidar. From adorable frocks for little girls and festive kurta sets for boys, to graceful designer kurtis for women and sharp tailored shirts for men, we take pride in celebrating every milestone of your life with style.',
  aboutHighlights: [
    'Handpicked authentic fabrics & premium tailoring',
    'Full family collection: Boys, Girls, Women & Mens',
    'Personalized WhatsApp consultation & sizing support',
    'Convenient store location in the heart of Bidar'
  ],
  whatsappCtaText: 'ORDER THROUGH WHATSAPP',
  whatsappPriceHiddenCtaText: 'ASK FOR PRICE ON WHATSAPP',
  whatsappOutOfStockCtaText: 'ASK IF AVAILABLE',
  normalEnquiryTemplate: "Hi, I'm interested in this product. Can I get more details?",
  priceEnquiryTemplate: "Hi, I'm interested in this product and would like to know the price and details.",
  showOutOfStockProducts: true,
  allowOutOfStockOrdering: false,
  hiddenProductsReturn404: false,
};
